FLAGS = -Wall

COMMON_DEPENDENCIES = 
SERVER_DEPENDENCIES =
CLIENT_DEPENDENCIES =

all: client.exe server.exe

client.exe: $(COMMON_DEPENDENCIES) $(CLIENT_DEPENDENCIES)
	gcc app/client.c -o client.out $(COMMON_DEPENDENCIES) $(CLIENT_DEPENDENCIES)

server.exe : $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES)
	gcc app/server.c -o server.out $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES)

$(COMMON_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

$(SERVER_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

$(CLIENT_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

clean:
	rm -f $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES) $(CLIENT_DEPENDENCIES)