FLAGS = -Wall

COMMON_DEPENDENCIES = 
SERVER_DEPENDENCIES =
CLIENT_DEPENDENCIES =

all: client.out server.out

client.out: $(COMMON_DEPENDENCIES) $(CLIENT_DEPENDENCIES)
	gcc app/inf150192c.c -o client.out $(COMMON_DEPENDENCIES) $(CLIENT_DEPENDENCIES)

server.out : $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES)
	gcc app/inf150192s.c -o server.out $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES)

$(COMMON_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

$(SERVER_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

$(CLIENT_DEPENDENCIES):
	gcc -c $@.c -o $@ $(FLAGS)

clean:
	rm -f $(COMMON_DEPENDENCIES) $(SERVER_DEPENDENCIES) $(CLIENT_DEPENDENCIES)